import { useRef } from "react";
import { BD, MT, G, row, RADIUS, TYPOGRAPHY, COLOR_PALETTE } from "../../../constants/design.js";

export function QrisSettingsTab({ settingsH }) {
  const imageRefs = useRef({});
  const methods = (settingsH.settings.paymentMethods || []).filter((method) => method.category === "qris");
  const images = settingsH.settings.qrisImages || {};
  return <div>
    <div style={{ fontSize: TYPOGRAPHY.label.fontSize, color: MT, fontWeight: 600, marginBottom: 10 }}>Kelola gambar QRIS untuk setiap metode pembayaran. Gambar akan ditampilkan di resi pelanggan.</div>{methods.length ? methods.map((method) => { const hasImage = Boolean(images[method.key]); return <div key={method.key} style={{ padding: 12, background: COLOR_PALETTE.primaryLight, borderRadius: RADIUS.md, marginBottom: 10, border: "1px solid #a8d5b8" }}><div style={{ ...row, marginBottom: 8 }}><span style={{ fontSize: TYPOGRAPHY.small.fontSize, fontWeight: 700 }}>{method.label}</span>{hasImage && <span style={{ fontSize: TYPOGRAPHY.label.fontSize, color: G, fontWeight: 600 }}>✓ Ada gambar</span>}</div>{hasImage && <div style={{ marginBottom: 8 }}><img src={images[method.key]} alt={`QRIS ${method.label}`} style={{ maxWidth: "100%", maxHeight: 150, borderRadius: RADIUS.md, border: `1px solid ${BD}` }} /></div>}<input id={`qris-file-${method.key}`} name={`qrisFile_${method.key}`} ref={(element) => { imageRefs.current[method.key] = element; }} type="file" accept="image/jpeg,image/png" onChange={(event) => event.target.files[0] && settingsH.handleQrisImageUpload(method.key, event.target.files[0])} style={{ display: "none" }} /><div style={{ display: "flex", gap: 6 }}><button onClick={() => imageRefs.current[method.key]?.click()} style={{ flex: 1, padding: "6px 10px", background: COLOR_PALETTE.infoLight, color: COLOR_PALETTE.info, border: "none", borderRadius: RADIUS.sm, cursor: "pointer", fontFamily: "inherit", fontSize: TYPOGRAPHY.label.fontSize, fontWeight: 600 }}>{hasImage ? "Ganti Gambar" : "Upload Gambar"}</button>{hasImage && <button onClick={() => settingsH.deleteQrisImage(method.key)} style={{ padding: "6px 10px", background: COLOR_PALETTE.dangerLight, color: COLOR_PALETTE.danger, border: "none", borderRadius: RADIUS.sm, cursor: "pointer", fontFamily: "inherit", fontSize: TYPOGRAPHY.label.fontSize, fontWeight: 600 }}>Hapus</button>}</div></div>; }) : <div style={{ fontSize: TYPOGRAPHY.small.fontSize, color: MT, textAlign: "center", padding: "10px 0" }}>Tidak ada metode QRIS yang tersedia</div>}</div>;
}
