import { BD, LT, MT, G, W, row, RADIUS, TYPOGRAPHY, COLOR_PALETTE } from "../../../constants/design.js";
import { fieldStyle, SaveButton } from "./shared.jsx";

export function ReceiptSettingsTab({ settingsH }) {
  const fields = settingsH.settings.receiptAdditionals || [];
  const customerEnabled = settingsH.settings.customerEnabled !== false;
  const paxEnabled = settingsH.settings.receiptPaxEnabled === true;
  const tableEnabled = settingsH.settings.receiptTableEnabled === true;
  // Custom header (below logo) & footer (bottom) text on the receipt.
  // Multi-line is supported; empty means the default receipt layout.
  const headerText = settingsH.settings.receiptHeaderText || "";
  const footerText = settingsH.settings.receiptFooterText || "";
  const headerFooterCard = <div style={{ padding: 12, background: COLOR_PALETTE.infoLight, borderRadius: RADIUS.md, marginBottom: 12, border: "1px solid #b8ccf0" }}>
    <div style={{ fontSize: TYPOGRAPHY.small.fontSize, fontWeight: 700, marginBottom: 4 }}>🏪 Header &amp; Footer Resi</div>
    <div style={{ fontSize: TYPOGRAPHY.label.fontSize, color: MT, marginBottom: 10 }}>Atur teks tambahan di bawah logo (header) dan di bagian paling bawah resi (footer). Logo diubah lewat tab "Nama Warung" atau klik logo di header aplikasi.</div>
    <div style={{ fontSize: TYPOGRAPHY.label.fontSize, fontWeight: 600, color: G, marginBottom: 6 }}>Header (di bawah logo):</div>
    <textarea id="receipt-header-text" name="receiptHeaderText" autoComplete="off" rows={2} value={settingsH.receiptHeaderInput} onChange={(event) => settingsH.setReceiptHeaderInput(event.target.value)} placeholder={"Contoh: Cabang Sukamaju\nTelp/WA: 0812-xxxx-xxxx"} style={{ ...fieldStyle, width: "100%", resize: "vertical", fontFamily: "inherit", marginBottom: 6, boxSizing: "border-box" }} />
    <div style={{ display: "flex", gap: 7, marginBottom: 12 }}>
      <SaveButton onClick={() => settingsH.setReceiptHeaderText(settingsH.receiptHeaderInput)} />
      {headerText ? <button onClick={() => { settingsH.setReceiptHeaderInput(""); settingsH.setReceiptHeaderText(""); }} style={{ padding: "8px 14px", background: COLOR_PALETTE.dangerLight, color: COLOR_PALETTE.danger, border: "none", borderRadius: RADIUS.md, cursor: "pointer", fontFamily: "inherit", fontSize: TYPOGRAPHY.small.fontSize, fontWeight: 700 }}>Hapus</button> : null}
    </div>
    <div style={{ fontSize: TYPOGRAPHY.label.fontSize, fontWeight: 600, color: G, marginBottom: 6 }}>Footer (paling bawah):</div>
    <textarea id="receipt-footer-text" name="receiptFooterText" autoComplete="off" rows={2} value={settingsH.receiptFooterInput} onChange={(event) => settingsH.setReceiptFooterInput(event.target.value)} placeholder={"Contoh: Terima kasih atas kunjungan Anda\nIG: @warungku"} style={{ ...fieldStyle, width: "100%", resize: "vertical", fontFamily: "inherit", marginBottom: 6, boxSizing: "border-box" }} />
    <div style={{ display: "flex", gap: 7 }}>
      <SaveButton onClick={() => settingsH.setReceiptFooterText(settingsH.receiptFooterInput)} />
      {footerText ? <button onClick={() => { settingsH.setReceiptFooterInput(""); settingsH.setReceiptFooterText(""); }} style={{ padding: "8px 14px", background: COLOR_PALETTE.dangerLight, color: COLOR_PALETTE.danger, border: "none", borderRadius: RADIUS.md, cursor: "pointer", fontFamily: "inherit", fontSize: TYPOGRAPHY.small.fontSize, fontWeight: 700 }}>Hapus</button> : null}
    </div>
  </div>;
  const customerCard = <div style={{ padding: 12, background: customerEnabled ? COLOR_PALETTE.primaryLight : LT, borderRadius: RADIUS.md, marginBottom: 12, border: `1px solid ${customerEnabled ? "#b8ccf0" : BD}` }}><div style={{ ...row, marginBottom: 8 }}><div style={{ fontSize: TYPOGRAPHY.small.fontSize, fontWeight: 700 }}>👤 Fitur Pelanggan</div></div><button onClick={() => settingsH.setCustomerEnabled(!customerEnabled)} style={{ width: "100%", padding: "8px 10px", background: customerEnabled ? G : BD, color: customerEnabled ? W : MT, border: "none", borderRadius: RADIUS.sm, cursor: "pointer", fontFamily: "inherit", fontSize: TYPOGRAPHY.small.fontSize, fontWeight: 700 }}>{customerEnabled ? "✓ Aktif" : "Nonaktif"}</button><div style={{ fontSize: TYPOGRAPHY.label.fontSize, color: MT, marginTop: 8 }}>Simpan nama & nomor telepon pelanggan di struk. Jika dimatikan, kolom pelanggan di kasir, detail open bill, dan baris PELANGGAN pada resi akan disembunyikan.</div></div>;
  const partyCard = <div style={{ padding:12, background:LT, borderRadius:RADIUS.md, marginBottom:12, border:`1px solid ${BD}` }}><div style={{ fontSize:TYPOGRAPHY.small.fontSize, fontWeight:700, marginBottom:8 }}>🍽️ Pax &amp; Meja</div><div style={{ display:"grid", gridTemplateColumns:"1fr 1fr", gap:8 }}>{[["receiptTableEnabled", "Nomor meja", tableEnabled], ["receiptPaxEnabled", "Jumlah Pax", paxEnabled]].map(([field, label, enabled]) => <button key={field} type="button" onClick={() => settingsH.setReceiptPartyField(field, !enabled)} style={{ padding:8, background:enabled?G:BD, color:enabled?W:MT, border:0, borderRadius:RADIUS.sm, cursor:"pointer", fontFamily:"inherit", fontSize:TYPOGRAPHY.label.fontSize, fontWeight:700 }}>{label}: {enabled?"Aktif":"Nonaktif"}</button>)}</div></div>;
  return <div>{headerFooterCard}{customerCard}{partyCard}<div style={{ fontSize: TYPOGRAPHY.label.fontSize, color: MT, fontWeight: 600, marginBottom: 10 }}>Atur field yang muncul di checkout dan resi. Toggle "Wajib" untuk membuat field required. Semua field dapat dihapus.</div>{fields.map((field) => <div key={field.key} style={{ padding: 10, background: COLOR_PALETTE.infoLight, borderRadius: RADIUS.md, marginBottom: 8, border: "1px solid #b8ccf0" }}><div style={{ ...row, marginBottom: 8 }}><div><span style={{ fontSize: TYPOGRAPHY.small.fontSize, fontWeight: 700 }}>{field.label}</span><div style={{ fontSize: TYPOGRAPHY.label.fontSize, color: MT }}>📋 Field Resi</div></div><button onClick={() => settingsH.deleteReceiptAdditional(field.key)} style={{ background: COLOR_PALETTE.dangerLight, color: COLOR_PALETTE.danger, border: "none", borderRadius: RADIUS.sm, padding: "3px 8px", cursor: "pointer", fontFamily: "inherit", fontSize: TYPOGRAPHY.label.fontSize, fontWeight: 600 }}>Hapus</button></div><button onClick={() => settingsH.toggleReceiptAdditionalRequired(field.key)} style={{ width: "100%", padding: "6px 10px", background: field.required ? G : BD, color: field.required ? W : MT, border: "none", borderRadius: RADIUS.sm, cursor: "pointer", fontFamily: "inherit", fontSize: TYPOGRAPHY.label.fontSize, fontWeight: 600 }}>{field.required ? "✓ Wajib di isi" : "Tidak wajib"}</button></div>)}<div style={{ marginTop: 16, paddingTop: 12, borderTop: `1px solid ${BD}` }}><div style={{ fontSize: TYPOGRAPHY.label.fontSize, fontWeight: 600, color: G, marginBottom: 8 }}>Tambah Field Baru:</div><div style={{ display: "flex", gap: 7 }}><input id="new-receipt-field-label" name="newReceiptFieldLabel" autoComplete="off" type="text" value={settingsH.newReceiptFieldLabel} onChange={(event) => settingsH.setNewReceiptFieldLabel(event.target.value)} onKeyDown={(event) => event.key === "Enter" && settingsH.addReceiptField()} placeholder="Nama field (e.g., Catatan, Alamat)" style={{ ...fieldStyle, flex: 1 }} /><select id="new-receipt-field-type" name="newReceiptFieldType" value={settingsH.newReceiptFieldType} onChange={(event) => settingsH.setNewReceiptFieldType(event.target.value)} style={fieldStyle}><option value="text">Text</option><option value="number">Number</option></select><SaveButton children="Tambah" onClick={settingsH.addReceiptField} /></div></div></div>;
}
