import { BD, LT, MT, G, W, row, RADIUS, TYPOGRAPHY, COLOR_PALETTE } from "../../../constants/design.js";
import { fieldStyle, SaveButton } from "./shared.jsx";

export function ReceiptSettingsTab({ settingsH }) {
  const fields = settingsH.settings.receiptAdditionals || [];
  const customerEnabled = settingsH.settings.customerEnabled !== false;
  const customerCard = <div style={{ padding: 12, background: customerEnabled ? COLOR_PALETTE.primaryLight : LT, borderRadius: RADIUS.md, marginBottom: 12, border: `1px solid ${customerEnabled ? "#b8ccf0" : BD}` }}><div style={{ ...row, marginBottom: 8 }}><div style={{ fontSize: TYPOGRAPHY.small.fontSize, fontWeight: 700 }}>👤 Fitur Pelanggan</div></div><button onClick={() => settingsH.setCustomerEnabled(!customerEnabled)} style={{ width: "100%", padding: "8px 10px", background: customerEnabled ? G : BD, color: customerEnabled ? W : MT, border: "none", borderRadius: RADIUS.sm, cursor: "pointer", fontFamily: "inherit", fontSize: TYPOGRAPHY.small.fontSize, fontWeight: 700 }}>{customerEnabled ? "✓ Aktif" : "Nonaktif"}</button><div style={{ fontSize: TYPOGRAPHY.label.fontSize, color: MT, marginTop: 8 }}>Simpan nama & nomor telepon pelanggan di struk. Jika dimatikan, kolom pelanggan di kasir, detail open bill, dan baris PELANGGAN pada resi akan disembunyikan.</div></div>;
  return <div>{customerCard}<div style={{ fontSize: TYPOGRAPHY.label.fontSize, color: MT, fontWeight: 600, marginBottom: 10 }}>Atur field yang muncul di checkout dan resi. Toggle "Wajib" untuk membuat field required. Semua field dapat dihapus.</div>{fields.map((field) => <div key={field.key} style={{ padding: 10, background: COLOR_PALETTE.infoLight, borderRadius: RADIUS.md, marginBottom: 8, border: "1px solid #b8ccf0" }}><div style={{ ...row, marginBottom: 8 }}><div><span style={{ fontSize: TYPOGRAPHY.small.fontSize, fontWeight: 700 }}>{field.label}</span><div style={{ fontSize: TYPOGRAPHY.label.fontSize, color: MT }}>📋 Field Resi</div></div><button onClick={() => settingsH.deleteReceiptAdditional(field.key)} style={{ background: COLOR_PALETTE.dangerLight, color: COLOR_PALETTE.danger, border: "none", borderRadius: RADIUS.sm, padding: "3px 8px", cursor: "pointer", fontFamily: "inherit", fontSize: TYPOGRAPHY.label.fontSize, fontWeight: 600 }}>Hapus</button></div><button onClick={() => settingsH.toggleReceiptAdditionalRequired(field.key)} style={{ width: "100%", padding: "6px 10px", background: field.required ? G : BD, color: field.required ? W : MT, border: "none", borderRadius: RADIUS.sm, cursor: "pointer", fontFamily: "inherit", fontSize: TYPOGRAPHY.label.fontSize, fontWeight: 600 }}>{field.required ? "✓ Wajib di isi" : "Tidak wajib"}</button></div>)}<div style={{ marginTop: 16, paddingTop: 12, borderTop: `1px solid ${BD}` }}><div style={{ fontSize: TYPOGRAPHY.label.fontSize, fontWeight: 600, color: G, marginBottom: 8 }}>Tambah Field Baru:</div><div style={{ display: "flex", gap: 7 }}><input id="new-receipt-field-label" name="newReceiptFieldLabel" autoComplete="off" type="text" value={settingsH.newReceiptFieldLabel} onChange={(event) => settingsH.setNewReceiptFieldLabel(event.target.value)} onKeyDown={(event) => event.key === "Enter" && settingsH.addReceiptField()} placeholder="Nama field (e.g., Catatan, Alamat)" style={{ ...fieldStyle, flex: 1 }} /><select id="new-receipt-field-type" name="newReceiptFieldType" value={settingsH.newReceiptFieldType} onChange={(event) => settingsH.setNewReceiptFieldType(event.target.value)} style={fieldStyle}><option value="text">Text</option><option value="number">Number</option></select><SaveButton children="Tambah" onClick={settingsH.addReceiptField} /></div></div></div>;
}
