import { useEffect, useState } from "react";
import { G, W, BD, MT, row, RADIUS, TYPOGRAPHY, COLOR_PALETTE } from "../../../constants/design.js";

export default function PrinterTab({ settingsH }) {
  const [loading, setLoading] = useState(false);
  const [width, setWidth] = useState(settingsH.settings.receiptPaperWidthMm || 80);
  useEffect(() => setWidth(settingsH.settings.receiptPaperWidthMm || 80), [settingsH.settings.receiptPaperWidthMm]);
  useEffect(() => { if (!settingsH.printerList.length && !loading) { setLoading(true); settingsH.openPrinterModal?.().finally(() => setLoading(false)); } }, [settingsH.printerList.length, loading, settingsH.openPrinterModal]);
  return <div><p style={{ fontSize: TYPOGRAPHY.label.fontSize, color: MT, fontWeight: 600 }}>Pilih printer thermal untuk mencetak resi. Pastikan driver printer sudah terinstall.</p><PrinterButton settingsH={settingsH} name="" label="Default Printer Sistem" />{settingsH.printerList.length ? settingsH.printerList.map((printer) => <PrinterButton key={printer.name} settingsH={settingsH} name={printer.name} label={<><span>{printer.name}</span>{settingsH.settings.printerName === printer.name && <span style={{ marginLeft: "auto", color: G }}>✓</span>}</>} />) : <div style={{ fontSize: TYPOGRAPHY.small.fontSize, color: MT, textAlign: "center", padding: 10 }}>Tidak ada printer terdeteksi. Pastikan driver terinstall.</div>}<div style={{ paddingTop: 12, borderTop: `1px solid ${BD}`, marginTop: 10 }}><b style={{ color: G, fontSize: TYPOGRAPHY.label.fontSize }}>Lebar Kertas Resi (mm):</b><div style={{ display: "flex", gap: 7, alignItems: "center", marginTop: 8 }}><input type="number" min="30" max="210" value={width} onChange={(e) => setWidth(e.target.value)} onKeyDown={(e) => e.key === "Enter" && settingsH.setReceiptPaperWidth(width)} style={{ width: 90, padding: 8, border: `1px solid ${BD}`, borderRadius: RADIUS.md }} /><button onClick={() => settingsH.setReceiptPaperWidth(width)} style={{ padding: "8px 14px", background: G, color: W, border: 0, borderRadius: RADIUS.md }}>Simpan</button>{[58, 80].map((value) => <button key={value} onClick={() => { setWidth(value); settingsH.setReceiptPaperWidth(value); }} style={{ padding: "6px 10px", background: Number(settingsH.settings.receiptPaperWidthMm) === value ? COLOR_PALETTE.primaryLight : W, border: `1px solid ${Number(settingsH.settings.receiptPaperWidthMm) === value ? G : BD}`, borderRadius: RADIUS.sm }}>{value}mm</button>)}</div><div style={{ fontSize: TYPOGRAPHY.label.fontSize, color: MT, marginTop: 8 }}>Default 80mm. Gunakan 58mm untuk printer thermal mini. Rentang 30-210mm.</div></div></div>;
}
function PrinterButton({ settingsH, name, label }) { const selected = settingsH.settings.printerName === name; return <button onClick={() => settingsH.selectPrinter(name)} style={{ width: "100%", padding: "8px 10px", border: `2px solid ${selected ? G : BD}`, borderRadius: RADIUS.md, background: selected ? COLOR_PALETTE.primaryLight : W, marginBottom: 6, textAlign: "left", ...row }}>{label}</button>; }